#!/usr/bin/env python
from distutils.core import setup

setup (name='wmcore',
       version='1.0',
       package_dir={'WMCore': 'src/python/WMCore'},
       packages=['WMCore',
                 'WMCore.MsgService',
                 'WMCore.MsgService.MySQL',
                 'WMCore.JobFactory',
                 'WMCore.JobSplitting',
                 'WMCore.WMBS',
                 'WMCore.WMBS.SQLite',
                 'WMCore.WMBS.SQLite.Jobs',
                 'WMCore.WMBS.SQLite.Workflow',
                 'WMCore.WMBS.SQLite.Fileset',
                 'WMCore.WMBS.SQLite.Locations',
                 'WMCore.WMBS.SQLite.Files',
                 'WMCore.WMBS.SQLite.Subscriptions',
                 'WMCore.WMBS.Actions',
                 'WMCore.WMBS.Actions.Fileset',
                 'WMCore.WMBS.Actions.Files',
                 'WMCore.WMBS.Actions.Subscriptions',
                 'WMCore.WMBS.WMBSAccountant',
                 'WMCore.WMBS.WMBSAllocater',
                 'WMCore.WMBS.WMBSAllocater.Allocaters',
                 'WMCore.WMBS.WMBSFeeder.Feeders',
                 'WMCore.WMBS.WMBSFeeder',
                 'WMCore.WMBS.MySQL',
                 'WMCore.WMBS.MySQL.Jobs',
                 'WMCore.WMBS.MySQL.Workflow',
                 'WMCore.WMBS.MySQL.Fileset',
                 'WMCore.WMBS.MySQL.Locations',
                 'WMCore.WMBS.MySQL.Files',
                 'WMCore.WMBS.MySQL.Subscriptions',
                 'WMCore.DataStructs',
                 'WMCore.WMBSFeeder.DBS',
                 'WMCore.WMBSFeeder.PhEDExNotifier',
                 'WMCore.WMBSFeeder.Fake',
                 'WMCore.WMBSFeeder',
                 'WMCore.Services.JSONParser',
                 'WMCore.Services.SiteDB',
                 'WMCore.Services',
                 'WMCore.Database'],)


