WMStats.Globals.importScripts([
    "js/GUI/Tables/WMStats.Table.js",
    "js/GUI/Tables/WMStats.DefaultRequestTable.js",
    "js/GUI/Tables/WMStats.ActiveRequestTable.js",
    "js/GUI/Tables/WMStats.AgentTable.js",
    "js/GUI/Tables/WMStats.SiteTable.js",
    "js/GUI/Tables/WMStats.JobSummaryTable.js",
    "js/GUI/Tables/WMStats.CampaignTable.js",
    "js/GUI/Tables/WMStats.AlertTable.js",
    "js/GUI/Tables/WMStats.TableEventHandler.js"
])
