name: Check Shell Script Syntax

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
    - name: Get Diff Action
      uses: technote-space/get-diff-action@v1.2.8
    - name: Install ShellCheck
      run: |
        sudo apt-get install shellcheck
      if: env.GIT_DIFF
    - name: Lint with ShellCheck
      run: |
        shellcheck --shell=bash -x ${{ env.GIT_DIFF }}
      if: env.GIT_DIFF
