#!/usr/bin/env python

import os

from WMQuality.Code import Code

# output of the log files
# prefix of the files in cvs
# quality script for using pylint:
qualityScript = '/home/fvlingen/programFiles/CMS_CVS/WMCORE/standards/test_style.sh'
# output file:
qualityReport = '/home/fvlingen/programFiles/CMS_CVS/WMCORE/standards/codeQuality.txt'
# rating threshold (min: 0, max 10)
threshold = 8

packages = {\
        
        'src/python/WMCore/WMBSFeeder':'metson',\
        'test/python/WMCore_t/Services_t':'ewv',\
        'src/python/WMCore/MsgService':'fvlingen',\
        'test/python':'fvlingen,metson',\
        'src/python/WMCore/WMBSFeeder/RunTransferNotifier':'jacksonj',\
        'src/python/WMQuality':'fvlingen',\
        'test/python/WMCore_t/JobSplitting_t':'metson',\
        'src/python/WMCore/Database':'metson',\
        'src/python/WMCore/WMBS/SQLite/Jobs':'jcgon',\
        'test/python/WMCore_t/WMBSFeeder_t':'metson',\
        'test/python/WMCore_t/Alerts_t':'sfoulkes',\
        'src/python/WMComponent/DBSUpload':'afaq',\
        'src/python/WMComponent/DBSBuffer':'afaq',\
        'src/python/WMCore/Agent':'fvlingen',\
        'src/python/WMCore/HTTPFrontEnd/':'valya',\
        'src/python/WMCore':'metson',\
        'test/python/WMCore_t/MsgService_t':'fvlingen',\
        'test/python/WMCore_t/WMBS_t/WMBSAccountant_t':'swakef',\
        'test/python/WMCore_t/HTTPFrontEnd_t':'valya',\
        'test/python/WMCore_t/WMBS_t':'metson',\
        'test/python/WMComponent_t/DBSUpload_t':'afaq',\
        'src/python/WMCore/WMBS/WMBSAccountant':'swakef',\
        'test/python/WMCore_t/SiteScreening_t':'ewv',\
        'src/python/WMCore/WMBS/WMBSFeeder':'swakef',\
        'test/python/WMCore_t/Trigger_t':'fvlingen',\
        'src/python/WMCore/WMBS/WMBSAllocater':'swakef',\
        'src/python':'fvlingen,metson',\
        'src/python/WMComponent/Proxy':'fvlingen',\
        'src/python/WMCore/JobSplitting':'metson',\
        'test/python/WMCore_t/ThreadPool_t':'fvlingen',\
        'src/python/WMCore/WMBS/SQLite/JobGroup':'jcgon',\
        'test/python/WMComponent_t/Proxy_t':'fvlingen',\
        'src/python/WMComponent/ErrorHandler':'fvlingen',\
        'src/python/WMCore/ThreadPool':'fvlingen',\
        'src/python/WMComponent':'fvlingen,metson',\
        'test/python/WMComponent_t':'fvlingen,metshon',\
        'test/python/WMCore_t/DataStructs_t':'jcgon',\
        'src/python/WMCore/WMBS':'metson',\
        'test/python/WMCore_t/WMBS_t/Performance_t':'jcgon',\
        'test/python/WMCore_t':'fvlingen,metson',\
        'src/python/WMCore/FwkJobReport':'fvlingen',\
        'src/python/WMCore/Services':'metson',\
        'test/python/WMComponent_t/DBSBuffer_t':'afaq',\
        'test/python/WMCore_t/HTTPFrontEnd_t':'valya',\
        'src/python/WMCore/DataStructs':'sfoulkes',\
        'src/python/WMCore/Services/JSONParser':'ewv',\
        'test/python/WMCore_t/Services_t/SiteDB_t':'ewv',\
        'test/python/WMComponent_t/ErrorHandler_t':'fvlingen',\
        'test/python/WMCore_t/Agent_t':'fvlingen',\
        'src/python/WMCore/Alerts':'sfoulkes',\
        'src/python/WMCore/Trigger':'fvlingen',\
        'test/python/WMCore_t/WMFactory_t':'fvlingen',\
        'src/python/WMCore/Services/SiteDB':'ewv',\
        'src/python/WMCore/WMBSFeeder/PhEDExNotifier':'gowdy',\
        'test/python/WMCore_t/FwkJobReport_t':'fvlingen',\
        'test/python/WMCore_t/Database_t':'metson',\
        'src/python/WMCore/SiteScreening':'ewv',\
}

code = Code(qualityScript, qualityReport, os.getenv('WMCOREBASE'), threshold, packages)
code.run()
code.summaryText()
        
