#!/bin/sh

# setup backend
source setup_mysql.sh
# generic clean
./cleanup.sh
# clean backend specific stuff
./cleanup_mysql.sh
# test
python conf_test_mysql.py
# generic clean
./cleanup.sh
# clean backend specific stuff
./cleanup_mysql.sh

echo ''
echo '======================================================'
echo 'mysql backend tested, starting oracle backend'
echo '======================================================'

# setup backend
source setup_oracle.sh
# test
python conf_test_oracle.py
